name: build-and-upload-tauri

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to rebuild (leave blank for the latest release)'
        required: false
        type: string
      publish:
        description: 'Publish the release after uploading bundles?'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write

jobs:
  build-tauri:
    # ─────── outputs so other jobs can reuse the ID ─────────
    outputs:
      release-id: ${{ steps.rel.outputs.id }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: '--target aarch64-apple-darwin'
          - platform: macos-latest
            args: '--target x86_64-apple-darwin'
          - platform: ubuntu-22.04
            args: ''
          - platform: windows-latest
            args: ''
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      # ── Resolve release ID only on manual trigger ─────────
      - name: Get release ID (manual trigger only)
        if: github.event_name == 'workflow_dispatch'
        id: rel
        uses: actions/github-script@v6
        with:
          script: |
            const tag = core.getInput('tag') || null
            const { owner, repo } = context.repo
            let release
            if (tag) {
              release = await github.rest.repos.getReleaseByTag({ owner, repo, tag })
            } else {
              release = await github.rest.repos.getLatestRelease({ owner, repo })
            }
            core.setOutput('id', release.data.id)

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install Ubuntu dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install front‑end dependencies
        run: npm install

      - name: Build & upload Tauri bundles
        uses: tauri-apps/tauri-action@v0.5.22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ github.event_name == 'workflow_dispatch'
            && steps.rel.outputs.id
            || github.event.release.id }}
          args: ${{ matrix.args }}

  publish-release:
    needs: build-tauri
    if: |
      github.event_name == 'release' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true')
    runs-on: ubuntu-latest
    steps:
      - name: Publish release
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              release_id: '${{ github.event_name == 'workflow_dispatch'
                              && needs.build-tauri.outputs.release-id
                              || github.event.release.id }}',
              draft: false,
              prerelease: false
            })
