name: Pre Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag for pre-release"
        required: true
      release_name:
        description: "Release title"
        required: true
      body:
        description: "Release notes"
        required: false

permissions:
  contents: write # notwendig für GitHub Release

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v1.6.0
        with:
          tag_name: ${{ inputs.tag_name }}
          name: ${{ inputs.release_name }}
          body: ${{ inputs.body }}
          draft: false
          prerelease: true
